# Ansible Playbook for Subutai Postgresql Blueprint
--- 

- hosts: postgres
  remote_user: root
  tasks:

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install dirmngr
      apt:
        name: dirmngr
        allow_unauthenticated: yes

    - name: Install cacerts
      apt:
        name: ca-certificates
        allow_unauthenticated: yes

    - name: Add postgres repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgres repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
        update_cache: true
        state: present

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - postgresql
        - postgresql-client
        - postgresql-contrib
        - python-dev
        - python-setuptools
        - python-virtualenv
        - python-pip
        - pgadmin4

    - name: Install psycopg2 python package
      pip:
        name: psycopg2 


