# Ansible Playbook for Subutai Postgresql Blueprint
--- 

- hosts: postgres
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
      with_items:
        - dirmngr
        - ca-certificates
        - sudo
        - locales

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    # -------------------------------------------------------------------------
    # Add the postgres repo, its key, and update cache
    # -------------------------------------------------------------------------

    - name: Add postgres repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgres repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
        update_cache: true
        state: present

    # -------------------------------------------------------------------------
    # Big ass install of all that might be needed
    # -------------------------------------------------------------------------

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - expect
        - postgresql
        - postgresql-client
        - postgresql-contrib
        - build-essential
        - libssl-dev
        - libffi-dev
        - libgmp3-dev
        - libpq-dev
        - python3-dev
        - python3-setuptools
        - python-virtualenv
        - python3-pip
        - apache2
        - libapache2-mod-wsgi-py3
        - pgadmin4

    # -------------------------------------------------------------------------
    # Create pgadmin user, dirs
    # -------------------------------------------------------------------------

    - name: Create pgadmin user
      user:
        name: pgadmin
        password: secret # @TODO replace me with user provided info
        groups:
          - postgres
          - www-data
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /var/lib/pgadmin

    - name: Create pgadmin directories
      file:
        path: "{{item}}"
        state: directory
        mode: 0755
        owner: pgadmin
      with_items:
        - /var/lib/pgadmin/sessions
        - /var/lib/pgadmin/storage
        - /var/log/pgadmin

    # -------------------------------------------------------------------------
    # Prepare Python3.5 based environment, install the stuff
    # -------------------------------------------------------------------------

    - name: Prepare python environment
      command: virtualenv -p /usr/bin/python3.5 --system-site-packages --always-copy /var/lib/pgadmin/env 
      become: yes
      become_user: pgadmin

    - name: Install psycopg2 python package
      pip:
        name: psycopg2
        executable: /usr/bin/pip3

    - name: Download pgadmin wheel file
      get_url:
        url: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v3.6/pip/pgadmin4-3.6-py2.py3-none-any.whl
        dest: /var/lib/pgadmin/pgadmin4-3.6-py2.py3-none-any.whl

    - name: Install pgadmin wheel package
      pip:
        name: /var/lib/pgadmin/pgadmin4-3.6-py2.py3-none-any.whl
        virtualenv: /var/lib/pgadmin/env

    # -------------------------------------------------------------------------
    # Upload, and exec configuration, expect scripts to respond to setup.py
    # -------------------------------------------------------------------------

    - name: Transfer local_config.py
      copy: 
        src: config_local.py
        dest: /var/lib/pgadmin/env/lib/python3.5/site-packages/pgadmin4
        owner: pgadmin
        mode: 0644

    - name: Transfer setup_expect.sh
      copy:
        src: setup_expect.sh
        dest: /var/lib/pgadmin/setup_expect.sh
        owner: pgadmin
        mode: 0755

    - name: Transfer setup_responses.exp
      copy:
        src: setup_responses.exp
        dest: /var/lib/pgadmin/setup_responses.exp
        owner: pgadmin
        mode: 0755

    - name: Prepare python environment
      command: ./setup_expect.sh 
      become: yes
      become_user: pgadmin

    # -------------------------------------------------------------------------
    # Upload, and exec configuration, expect scripts to respond to setup.py
    # -------------------------------------------------------------------------

    # Might go away

    - name: Restart apache
      service: 
        name: apache2
        state: restarted


