# Ansible Playbook for Subutai Postgresql Blueprint
--- 

- hosts: postgres
  remote_user: root
  tasks:

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
        update_cache: true
        with_items:
          - dirmngr
          - ca-certificates
          - sudo
          - locales

    - name: Setup locale properly
      locale_gen:
        name: us_US.UTF-8
        state: present

    - name: Add postgres repository key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add postgres repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
        update_cache: true
        state: present

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - postgresql
        - postgresql-client
        - postgresql-contrib
        - python-dev
        - python-setuptools
        - python-virtualenv
        - python-pip
        - pgadmin4
        - apache2
        - libgmp3-dev
        - libpq-dev
        - libapache2-mod-wsgi-py3

    - name: Install psycopg2 python package
      pip:
        name: psycopg2 

    - name: Create pgadmin user
      user:
        name: pgadmin
        password: secret
        groups:
          - postgres
        state: present
        system: no
        createhome: yes
        home: /var/lib/pgadmin

    - name: Create pgadmin directories
      file:
        path: "{{item}}"
        state: directory
        mode: 0755
        with_items:
          - /var/lib/pgadmin/sessions
          - /var/lib/pgadmin/storage
          - /var/log/pgadmin
        owner: pgadmin

    - name: Restart apache
      service: 
        name: apache2
        state: restarted


